# Generated by Django 5.0.4 on 2024-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custonmuser',
            name='ages',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custonmuser',
            name='gender',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custonmuser',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
