# Generated by Django 5.0.4 on 2024-04-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_custonmuser_ages_custonmuser_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustonmUser',
            new_name='CustomUser',
        ),
    ]
