# Generated by Django 5.0.4 on 2024-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0003_rename_custonmuser_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ages',
            field=models.SmallIntegerField(choices=[(1, '10s'), (2, '20s'), (3, '30s'), (4, '40s'), (5, '50s'), (6, '60s'), (7, '70s over')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
